<a href="https://colab.research.google.com/github/Yasmic/MYDeepLearning/blob/main/Numpybasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Numpy arrays 
Broad casting possible values can be applied to all the eliments of list


In [1]:
import numpy as np

In [ ]:
np.array(5)

array(5)

In [ ]:
vp=np.array([5,6,7,8])

In [ ]:
print(vp)

[5 6 7 8]


In [ ]:
print(vp+1)

[6 7 8 9]


In [ ]:
vp1=[5,6,7,8]

In [ ]:
print(vp1[0])

5


In [ ]:
vp2=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [ ]:
print(vp2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
vp2.shape

(3, 3)

#Random matrix or value generation using randint

In [ ]:
x = np.random.randint(100,size=(1,6,5))

In [ ]:
print(x)

[[[50 27 14 41 58]
  [65 36 10 86 43]
  [11  2 51 80 32]
  [54  0 38 19 46]
  [42 56 60 77 30]
  [24  2  3 94 98]]]


#Reshaping the matrix
Using reshape or [None, :]

In [ ]:
x.shape

(1, 6, 5)

In [ ]:
s = np.array(5)

In [ ]:
s.shape

()

In [ ]:
v = np.array([1,2,3,4])

In [ ]:
v.shape

(4,)

In [ ]:
x=v.reshape(1,4)

In [ ]:
x=v.reshape(4,1)

In [ ]:
x

array([[1],
       [2],
       [3],
       [4]])

In [ ]:
x[1][0]

2

In [ ]:
x = v[None, :]

In [ ]:
x.shape

(1, 4)

In [ ]:
x=v[:,None]

In [ ]:
x.shape

(4, 1)

# Matrix multiplication
using dot and matmul , when the matrix is 2D the results are same for both dot and matmul, but larger dimensions results will be different
Column of first matrix should be equal to row of 2nd matrix

In [ ]:
a = np.array([[1,2,3,4],[5,6,7,8]])

In [ ]:
a.shape

(2, 4)

In [ ]:
b = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [ ]:
b.shape

(4, 3)

In [ ]:
c= np.matmul(a, b)

In [ ]:
c

array([[ 70,  80,  90],
       [158, 184, 210]])

In [ ]:
c=np.dot(a,b)

In [ ]:
c

array([[ 70,  80,  90],
       [158, 184, 210]])

In [ ]:
a=np.random.randint(100,size=(1,3,2))

In [ ]:
a.shape

(1, 3, 2)

In [ ]:
b=np.random.randint(100,size=(1,2,3))

In [ ]:
b.shape

(1, 2, 3)

In [ ]:
c=np.dot(a,b)

In [ ]:
c

array([[[[6693, 2944, 3602]],

        [[2594,  736, 1524]],

        [[6636, 4439, 3091]]]])

In [ ]:
c.shape

(1, 3, 1, 3)

In [ ]:
c=np.matmul(a,b)

In [ ]:
c.shape

(1, 3, 3)

In [ ]:
c

array([[[3534, 3370, 1802],
        [5508, 4855, 2239],
        [4911, 3822, 1270]]])

# Transpose
Getting the transpose of a matrix is really easy in NumPy. Simply access its T attribute. There is also a transpose() function which returns the same thing, but you’ll rarely see that used anywhere because typing T is so much easier. :)

In [ ]:
m = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [ ]:
m

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
m.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [ ]:
   input_array=[-1,2,7]


In [ ]:
input_array=np.array(input_array)

In [ ]:
input_array

array([-1,  2,  7])

In [ ]:
input_array=input_array[None,:]

In [ ]:
input_array.shape

(1, 3)

In [ ]:
input_array

array([[-1,  2,  7]])

In [ ]:
input_array.min()

-1

In [ ]:
inputs_minus_min=input_array-input_array.min()

In [ ]:
inputs_minus_min

array([[0, 3, 8]])

In [ ]:
inputs_minus_min.max()

8

In [ ]:
inputs_div_max=inputs_minus_min/inputs_minus_min.max()

In [ ]:
inputs_div_max

array([[0.   , 0.375, 1.   ]])

#find average in numpy

In [ ]:
values=[1,3,4]

In [ ]:
values=np.array(values)

In [ ]:
values.mean()

2.6666666666666665

In [ ]:
(1+3+4)/3

2.6666666666666665

#Zip function

In [7]:
number_list = [1, 2, 3]
str_list = ['one', 'twenty', 'three']

# No iterables are passed
result = zip()

# Converting iterator to list
result_list = list(result)
#print(result_list)

# Two iterables are passed
result = zip(number_list, str_list)

for resultty in zip(number_list,str_list):
  print(resultty)
# Converting iterator to set or list
result_set = list(result)
print(result_set)

(1, 'one')
(2, 'twenty')
(3, 'three')
[(1, 'one'), (2, 'twenty'), (3, 'three')]


In [8]:
x=np.random.randint(100,size=(3,2))

In [9]:
x

array([[26, 91],
       [65, 60],
       [37, 69]])

In [14]:
x[0,1]

91

In [11]:
x[1]

array([65, 60])

In [21]:
x1=-4
x2=5
x=4*x1+5*x2 - 9 
1/(1+np.exp(-x))

0.5

In [23]:
import numpy as np

# Write a function that takes as input a list of numbers, and returns
# the list of values given by the softmax function.
def softmax(L):
    sum=np.exp(L)
    P=[]
    for i in range(len(L)):
        P.append(np.exp(L[i])/np.sum(sum))
    return P



    #otherway
    import numpy as np

# Write a function that takes as input a list of numbers, and returns
# the list of values given by the softmax function.
def softmax(L):
    sum=np.exp(L)
    return (np.exp(L)/np.sum(sum))

#Cross Entropy

In [ ]:
import numpy as np

# Write a function that takes as input two lists Y, P,
# and returns the float corresponding to their cross-entropy.
def cross_entropy(Y, P):
   Y=np.array(Y)
   P=np.array(P)
   CrossEntropy=-np.sum(Y*np.log(P)+(1-Y)*np.log(1-P))
   return CrossEntropy